import { readFileSync } from 'fs'
import { join } from 'path'
import { pathToFileURL } from 'url'
import { parentPort, workerData } from 'worker_threads'
import type { WorkerData, WorkerReply, WorkerRequest } from './protocol'

/**
 * Runs the Phonon WebAssembly module off the main thread.
 *
 * The module generates one 80 ms frame per call and never yields, so running
 * it on the event loop of the server would hold every other call for the
 * length of a sentence. Here the frames are produced one at a time, with a
 * turn of this thread's event loop between two of them, which is where a
 * cancel coming from the main thread is heard.
 */

interface Job {
  id: number
  voicePath: string
  text: string
  temperature: number
  seed: number
}

// The wasm-bindgen glue, generated by scripts/build-wasm.sh
interface PhononModel {
  add_voice(voice: Uint8Array): number
  start_generation(
    voiceIndex: number,
    text: string,
    temperature: number,
    seed: bigint
  ): number
  next_chunk(): number | undefined
  generation_step(): Float32Array | undefined
  stop_generation(): void
  sample_rate(): number
}

interface PhononModule {
  initSync(options: { module: Uint8Array }): void
  Model: new (
    weights: Uint8Array,
    tokenizer: Uint8Array,
    config: Uint8Array | undefined,
    quant: string,
    language: string,
    rewrites: string | undefined
  ) => PhononModel
}

const port = parentPort!
const data = workerData as WorkerData

const queue: Job[] = []
const cancelled = new Set<number>()
// Voices are registered once, the model keeps their state by index
const voiceIndexes = new Map<string, number>()
let model: PhononModel | undefined
let running = false

function reply(message: WorkerReply, transfer?: ArrayBuffer[]) {
  port.postMessage(message, transfer)
}

function nextTurn(): Promise<void> {
  return new Promise((resolve) => setImmediate(resolve))
}

async function load() {
  const glue: PhononModule = await import(
    pathToFileURL(join(data.wasmDir, 'phonon_tts.js')).href
  )
  glue.initSync({
    module: readFileSync(join(data.wasmDir, 'phonon_tts_bg.wasm')),
  })
  model = new glue.Model(
    readFileSync(data.files.weights),
    readFileSync(data.files.tokenizer),
    data.files.config ? readFileSync(data.files.config) : undefined,
    data.quant,
    data.language,
    data.rewrites
  )
  reply({ type: 'ready', sampleRate: model.sample_rate() })
}

function getVoiceIndex(model: PhononModel, path: string): number {
  let index = voiceIndexes.get(path)
  if (index === undefined) {
    index = model.add_voice(readFileSync(path))
    voiceIndexes.set(path, index)
  }
  return index
}

async function generate(model: PhononModel, job: Job) {
  model.start_generation(
    getVoiceIndex(model, job.voicePath),
    job.text,
    job.temperature,
    BigInt(job.seed)
  )
  while (model.next_chunk() !== undefined) {
    while (true) {
      if (cancelled.has(job.id)) {
        model.stop_generation()
        return
      }
      const samples = model.generation_step()
      if (!samples) break
      reply({ type: 'audio', id: job.id, samples }, [
        samples.buffer as ArrayBuffer,
      ])
      await nextTurn()
    }
  }
}

async function drain() {
  if (running || !model) return
  running = true
  while (queue.length) {
    const job = queue.shift()!
    if (!cancelled.has(job.id)) {
      try {
        await generate(model, job)
      } catch (error) {
        reply({ type: 'failed', id: job.id, message: String(error) })
      }
    }
    cancelled.delete(job.id)
    reply({ type: 'done', id: job.id })
  }
  running = false
}

port.on('message', (message: WorkerRequest) => {
  switch (message.type) {
    case 'generate':
      queue.push(message)
      drain()
      break
    case 'cancel':
      cancelled.add(message.id)
      break
  }
})

load()
  .then(drain)
  .catch((error) => reply({ type: 'loadFailed', message: String(error) }))
